backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
collections:
  - name: "faculty"
    label: "Faculty"
    folder: "_faculty/"
    slug: "{{first_name}}-{{last_name}}"
    create: true
    editor:
      preview: false
    summary: "{{first_name}} {{last_name}}"
    fields:
      - name: first_name
        label: First Name
      - name: last_name
        label: Last Name
      - name: position
        label: Position
      - name: email
        label: Email
      - name: phone
        label: Phone
